services:
  dev:
    build:
      context: ..
      dockerfile: docker/dev.dockerfile
    volumes:
      - ..:/project
      - $SSH_AUTH_SOCK:/ssh-agent
    ports:
      - "8888:8888"
      - "5000:5000"
    environment:
      - PYTHONPATH=/project
      - SSH_AUTH_SOCK=/ssh-agent
    command: python -m mlflow server --port 5000 --host 0.0.0.0 --backend-store-uri /project/mlflow/runs --default-artifact-root /project/mlflow/artifacts & sleep infinity
