services:
  dev:
    build:
      context: ..
      dockerfile: docker/dev.dockerfile
    volumes:
      - ../workspace/src:/workspace/src
      - ../data:/data
      - ../workspace/experiments:/workspace/experiments
      - ../workspace/notebooks:/workspace/notebooks
    ports:
      - "8888:8888"
      - "5000:5000"
    environment:
      - PYTHONPATH=/workspace
    command: sleep infinity