services:
  dev:
    build:
      context: ..
      dockerfile: docker/dev.dockerfile
    volumes:
      - ..:/project
      - $SSH_AUTH_SOCK:/ssh-agent
    ports:
      - "8888:8888"
      - "5000:5000"
    environment:
      - PYTHONPATH=/project
      - SSH_AUTH_SOCK=/ssh-agent
      - MLFLOW_PORT=5000
      - MLFLOW_ARTIFACTS_DIR=mlflow/artifacts
    command: python -m mlflow server --port ${MLFLOW_PORT} --host 0.0.0.0 --backend-store-uri /project/mlflow/runs --default-artifact-root /project/${MLFLOW_ARTIFACTS_DIR} & sleep infinity
